run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 3m

service:
  prepare:
    - apt-get update && apt-get install -y gcc pkg-config libvips-dev

linters:
  enable:
    - deadcode
    - errcheck
    - gas
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosimple
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - unused
  fast: false
