run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 3m
  go: '1.18'

linters:
  enable:
    - deadcode
    - errcheck
    - funlen
    - gas
    - gochecknoinits
    - gocritic
    - gocyclo
    - gofmt
    - revive
    - gosec
    - gosimple
    - ineffassign
    - govet
    - megacheck
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
  fast: false
