language: go

os: linux
dist: xenial

go:
  - 1.11.x
  - 1.12.x
  - 1.x

cache:
  apt:

addons:
  apt:
    packages:
      - gobject-introspection
      - gtk-doc-tools
      - libcfitsio3-dev
      - libfftw3-dev
      - libgif-dev
      - libgs-dev
      - libgsf-1-dev
      - libmatio-dev
      - libopenslide-dev
      - liborc-0.4-dev
      - libpango1.0-dev
      - libpoppler-glib-dev
      - libwebp-dev
      - libvips-dev

before_install:
  - pkg-config --modversion vips
  - go get -u github.com/mattn/goveralls

install:
  - go get golang.org/x/lint/golint
  - go get -v github.com/go-lintpack/lintpack/...
  - go get -v github.com/go-critic/go-critic/...
  - go get -v github.com/fzipp/gocyclo
  - go get -v github.com/gordonklaus/ineffassign
  - lintpack build -o $GOPATH/bin/gocritic -linter.name='gocritic' github.com/go-critic/go-critic/checkers

script:
  - make test

after_success:
  - goveralls -coverprofile=./coverage/cover.out -service=travis-ci
