name: Lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install -y gobject-introspection gtk-doc-tools libcfitsio-dev libfftw3-dev libgif-dev \
                                  libgs-dev libmatio-dev libopenslide-dev liborc-0.4-dev libpango1.0-dev \
                                  libpoppler-glib-dev libwebp-dev libvips-dev && \
          sudo pkg-config --modversion vips
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
